/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export function __wbg_extendedkey_free(a: number): void;
export function extendedkey_public_raw(a: number, b: number): void;
export function extendedkey_private_raw(a: number, b: number): void;
export function extendedkey_public_hexstring(a: number, b: number): void;
export function extendedkey_private_hexstring(a: number, b: number): void;
export function extendedkey_public_base64(a: number, b: number): void;
export function extendedkey_private_base64(a: number, b: number): void;
export function extendedkey_address(a: number, b: number): void;
export function generateMnemonic(a: number, b: number): void;
export function isMnemonicValid(a: number, b: number, c: number): number;
export function keyFromMnemonic(a: number, b: number, c: number, d: number, e: number, f: number): void;
export function keyDerive(a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number, i: number): void;
export function keyDeriveFromSeed(a: number, b: number, c: number, d: number): void;
export function keyRecover(a: number, b: number, c: number): void;
export function keyRecoverBLS(a: number, b: number, c: number): void;
export function transactionSerialize(a: number, b: number): void;
export function transactionSerializeRaw(a: number, b: number): void;
export function transactionParse(a: number, b: number, c: number): void;
export function transactionSign(a: number, b: number, c: number): void;
export function transactionSignLotus(a: number, b: number, c: number): void;
export function transactionSignRaw(a: number, b: number, c: number): void;
export function verifySignature(a: number, b: number, c: number): void;
export function signVoucher(a: number, b: number, c: number, d: number): void;
export function createVoucher(a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number, i: number, j: number, k: number, l: number, m: number, n: number): void;
export function serializeParams(a: number, b: number): void;
export function deserializeParams(a: number, b: number, c: number, d: number, e: number, f: number): void;
export function deserializeConstructorParams(a: number, b: number, c: number, d: number, e: number): void;
export function verifyVoucherSignature(a: number, b: number, c: number, d: number, e: number): void;
export function serializeVoucher(a: number, b: number): void;
export function deserializeVoucher(a: number, b: number, c: number): void;
export function computeProposalHash(a: number, b: number): void;
export function getCid(a: number, b: number): void;
export function __wbindgen_malloc(a: number): number;
export function __wbindgen_realloc(a: number, b: number, c: number): number;
export function __wbindgen_add_to_stack_pointer(a: number): number;
export function __wbindgen_free(a: number, b: number): void;
export function __wbindgen_exn_store(a: number): void;
